W4D2/cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

W4D2/cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  validates :birth_date, :color, :name, :sex, presence: true
  validates :sex, inclusion: { in: ['M', 'F'] }

  COLORS = ["grey", "brown", "yellow", "white", "black", "orange"]

  def self.colors
    COLORS
  end

  has_many :rental_requests,
    foreign_key: :cat_id,
    primary_key: :id,
    class_name: :CatRentalRequest,
    dependent: :destroy
end

W4D2/cats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#

class CatRentalRequest < ApplicationRecord
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: ['PENDING', 'APPROVED', 'DENIED'] }
  validate :does_not_overlap_approved_request

  belongs_to :cat,
    foreign_key: :cat_id,
    primary_key: :id,
    class_name: :Cat

  def overlapping_requests
    self.cat.rental_requests.where.not(id: id).where('cat_rental_requests.start_date BETWEEN ? AND ?', start_date, end_date)
    .or(self.cat.rental_requests.where.not(id: id).where('cat_rental_requests.end_date BETWEEN ? AND ?', start_date, end_date ))
    .or(self.cat.rental_requests.where.not(id: id).where('? BETWEEN cat_rental_requests.start_date AND cat_rental_requests.end_date', start_date))
    .or(self.cat.rental_requests.where.not(id: id).where('? BETWEEN cat_rental_requests.start_date AND cat_rental_requests.end_date', end_date))
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: 'APPROVED')
  end

  def does_not_overlap_approved_request
    if overlapping_approved_requests.exists?
      errors.add(:overlapping_requests, "can't overlap with existing approved Cat Rental Requests for the same cat")
    end
  end
end

W4D2/cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
end

W4D2/cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all

    render :index
  end

  def create
    @cat = Cat.new(cats_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render plain: @cat.errors.full_messages, status: 422
    end
  end

  def new
    @cat = Cat.new

    render :new
  end

  def edit
    @cat = Cat.find_by(id: params[:id])

    if @cat.nil?
      render plain: "Cat doesn't exist", status: 404
    else
      render :edit
    end
  end

  def show
    @cat = Cat.find_by(id: params[:id])

    if @cat.nil?
      render plain: "Cat doesn't exist", status: 404
    else
      render :show
    end
  end

  def update
    @cat = Cat.find_by(id: params[:id])

    if @cat.nil?
      render plain: "Cat doesn't exist", status: 404
    elsif @cat.update_attributes(cats_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end

  end

  def destroy

  end

  private

  def cats_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

W4D2/cats/app/views/cats/_cat.html.erb
<table>
  <tr>
    <th> birth_date </th>
    <th> color </th>
    <th> name </th>
    <th> sex </th>
    <th> description </th>
  </tr>

  <tr>
    <th> <%= cat.birth_date %> </th>
    <th> <%= cat.color %> </th>
    <th> <%= cat.name %> </th>
    <th> <%= cat.sex %> </th>
    <th> <%= cat.description %> </th>
  </tr>
</table>

W4D2/cats/app/views/cats/_form.html.erb
<% if cat.persisted? %>
<%    action_url = cat_url%>
<% else %>
<%    action_url = cats_url %>
<% end %>

<form action="<%=action_url%>" method="post">
  <% if cat.persisted? %>
    <input type = 'hidden' name = '_method' value = 'PATCH'/>
  <% end %>
  <label for="birth_date">birth date:</label>
  <input type = "date" id = "birth_date" name = "cat[birth_date]" value = "<%=cat.birth_date%>"/>
  <br>
  <label for="color">color:</label>
  <select name="cat[color]">
    <option disabled> -- Select A Color -- </option>
    <% Cat.colors.each do |color| %>
    <option <%= cat.color == color ? "selected" : "" %> value="<%= color %>"> <%= color.capitalize %> </option>
    <% end %>
  </select>
  <br>

  <label for="name">name:</label>
  <input type = "text" id = "name" name = "cat[name]" value = "<%=cat.name%>"/>
  <br>

  <label for="sex">sex:</label>
  <input <%= cat.sex == 'M' ? "checked" : "" %> type = "radio" name = "cat[sex]" value = "M"/> M
  <input <%= cat.sex == 'F' ? "checked" : "" %> type = "radio" name = "cat[sex]" value = "F"/> F
  <br>

  <label for="description">description:</label>
  <textarea id = "description" name = "cat[description]"><%=cat.description%></textarea>
  <br>

  <input type="submit" value="Save Edits">
</form>

W4D2/cats/app/views/cats/edit.html.erb
<%= render 'form', cat: @cat %>

W4D2/cats/app/views/cats/index.html.erb
<% @cats.each do |cat|%>
<ul>
    <li> name: <%= cat.name %> </li>
    <li> link: <%= link_to 'Show cat detail', cat_url(cat) %> </li>
</ul>
<% end %>

W4D2/cats/app/views/cats/new.html.erb
<%= render 'form', cat: @cat %>

W4D2/cats/app/views/cats/show.html.erb
<%= render('cat', { cat: @cat }) %>
<%= link_to "Edit this cat", edit_cat_url %> <br>
<%= link_to "Back to all cats", cats_url %>