W5D2/redditclone/config/routes.rb
Rails.application.routes.draw do

  resources :users
  resource :session
  resources :subs do
    resources :posts, only: [:create]
  end
  resources :posts, only: [:destroy]
  resources :posts, only: [:create, :edit, :update, :new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

W5D2/redditclone/app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :post

  belongs_to :user
end

W5D2/redditclone/app/models/moderator_membership.rb
class ModeratorMembership < ApplicationRecord

  belongs_to :user
  belongs_to :sub
  
end

W5D2/redditclone/app/models/post.rb
class Post < ApplicationRecord
  validates :title, :url, :content, :author, presence: true

  has_many :post_subs

  has_many :subs,
    through: :post_subs,
    source: :sub

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  has_many :comments

end

W5D2/redditclone/app/models/post_sub.rb
class PostSub < ApplicationRecord

  belongs_to :post

  belongs_to :sub
end

W5D2/redditclone/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, presence: true

  has_many :post_subs

  has_many :posts,
    through: :post_subs,
    source: :post

  has_many :moderator_memberships

  has_many :moderators,
    through: :moderator_memberships,
    source: :user

end

W5D2/redditclone/app/models/user.rb
class User < ApplicationRecord

  after_initialize :ensure_token

  validates :username, :email, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password

  has_many :comments
  has_many :moderator_memberships

  def self.find_by_creds(username, password)
    user = User.find_by_username(username)
    if user.nil?
      return nil
    else
      return user if user.password?(password)
    end
    nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end

  def ensure_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

end

W5D2/redditclone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def login(user)
    session[:session_token] = user.reset_session_token
  end

  def logout
    current_user.try(:reset_session_token)
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def ensure_logged_in
    flash[:errors] = ['Please login'] unless logged_in?
    redirect_to new_session_url unless logged_in?
  end
end

W5D2/redditclone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @subs = Sub.all
  end

  def create
    debugger
    post = Post.new(post_params)
    post.author_id = current_user.id
    destination = subs_url
    if params[:sub_id]
      create_post_subs(post, [params[:sub_id]])
      destination = sub_url(params[:sub_id])
    elsif params[:subs]
      create_post_subs(post, params[:subs])
    else
      #screwed

    end
    unless post.save
      flash[:errors] = post.errors.full_messages
    end
    redirect_to destination
  end

  def destroy
    post = Post.find(params[:id])
    post.post_subs.delete(PostSub.find_by(post_id: post.id, sub_id: params[:sub_id]))
    if post.post_subs.empty?
      post.destroy
    end
    redirect_to sub_url(params[:sub_id])
  end

  private

  def create_post_subs(post, subs_ids)
    subs_ids.each do |sub_id|
      post.subs << Sub.find_by_id(sub_id)
    end
  end

  def post_params
    params.require(:post).permit(:title, :url, :content)
  end
end

W5D2/redditclone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_creds(user_params[:username], user_params[:password])

    unless user.nil?
      login(user)
      session[:session_token] = user.session_token
      redirect_to subs_url
    else
      flash[:errors] = ["Invalid Username or Password"]
      render :new
    end
  end

  def new
    render :new
  end

  def destroy
    logout
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

W5D2/redditclone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :set_sub, only: [:show, :edit, :update, :destroy]
  before_action :ensure_logged_in
  # GET /subs
  # GET /subs.json
  def index
    @subs = Sub.all
  end

  # GET /subs/1
  # GET /subs/1.json
  def show
    @posts = @sub.posts
  end

  # GET /subs/new
  def new
    @sub = Sub.new
  end

  # GET /subs/1/edit
  def edit
  end

  # POST /subs
  # POST /subs.json
  def create
    @sub = Sub.new(sub_params)

    if @sub.save
      @sub.moderators << current_user
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  # PATCH/PUT /subs/1
  # PATCH/PUT /subs/1.json
  def update
    respond_to do |format|
      if @sub.update(sub_params)
        format.html { redirect_to @sub, notice: 'Sub was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub }
      else
        format.html { render :edit }
        format.json { render json: @sub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subs/1
  # DELETE /subs/1.json
  def destroy
    @sub.destroy
    respond_to do |format|
      format.html { redirect_to subs_url, notice: 'Sub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub
      @sub = Sub.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_params
      params.require(:sub).permit(:title, :description)
    end
end

W5D2/redditclone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      login(user)
      redirect_to subs_url
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  def index
    render :index
  end

  def show
    @user = User.find_by_id(params[:id])
    render :show
  end

  def destroy

  end

  def edit
  end

  def update
  end

  def user_params
    params.require(:user).permit(:email, :username, :password)
  end
end

W5D2/redditclone/app/helpers/application_helper.rb
module ApplicationHelper
def auth_token
  "<input type=\"hidden\" name=\"authenticity_token\"
  value=\"#{form_authenticity_token}\">".html_safe
end
end

W5D2/redditclone/app/helpers/posts_helper.rb
module PostsHelper
end

W5D2/redditclone/app/helpers/subs_helper.rb
module SubsHelper
end

W5D2/redditclone/app/views/posts/new.html.erb
<h2>Create a new post</h2>

<form action="<%= posts_url %>" method="post">
  <%= auth_token %>

  <label>Title
    <input type="text" name="post[title]">
  </label>

  <label>URL
    <input type="text" name="post[url]">
  </label>

  <label>content
    <input type="text" name="post[content]">
  </label>

  <ul>
  <% @subs.each do |sub|%>
  <li>
    <label> <%= sub.title %>
    <input type="checkbox" name="subs[]" value="<%= sub.id%>">
    </label>
    </li>
  <% end %>
</ul>
  <input type="submit" value="Create a post">

</form>

W5D2/redditclone/app/views/subs/_form.html.erb
<h2>Create a sub</h2>


<form class="" action="<%= subs_url %>" method="post">
  <%= auth_token %>

  <label>Title
    <input type="text" name="sub[title]">
  </label>

  <label>description
    <input type="text" name="sub[description]">
  </label>

  <input type="submit" value="create sub">

</form>

W5D2/redditclone/app/views/subs/edit.html.erb
<h1>Editing Sub</h1>

<%= render 'form', sub: @sub %>

<%= link_to 'Show', @sub %> |
<%= link_to 'Back', subs_path %>

W5D2/redditclone/app/views/subs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subs.each do |sub| %>
      <tr>
        <td><%= link_to "#{sub.title}", sub %></td>
        <td><%= link_to 'Edit', edit_sub_path(sub) %></td>
        <td><%= link_to 'Destroy', sub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub', new_sub_path %>

W5D2/redditclone/app/views/subs/new.html.erb
<h1>New Sub</h1>

<%= render 'form', sub: @sub %>

<%= link_to 'Back', subs_path %>

W5D2/redditclone/app/views/subs/show.html.erb
<p id="notice"><%= notice %></p>
<%= @sub.title %>
<%= @sub.description %>

<%= link_to 'Edit', edit_sub_path(@sub) %> |
<%= link_to 'Back', subs_path %>

<br>

<table>
  <thead>
    <tr>
      <th> Moderators</th>
    </tr>
  </thead>
  <% @sub.moderators.each do |mod| %>

  <tr>
    <td>
      <%= mod.username %>
    </td>
  </tr>
  <% end %>
</table>

<table>
  <thead>
    <tr>
      <th colspan="2"> Posts </th>
    </tr>
    <tr>
      <th colspan="2"> Create Post</th>
    </tr>
    <tr>
      <th colspan="2">
        <form action="<%= sub_posts_url(@sub) %>" method="post">
          <%= auth_token %>
          <label>Title
            <input type="text" name="post[title]" value="">
          </label>
          <label>URL
            <input type="text" name="post[url]" value="">
          </label>
          <label>Content
            <input type="text" name="post[content]" value="">
          </label>
          <input type="submit" name="Create Post">
        </form>
    </th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= "#{post.title}"%></td>
        <td><%= post.url %></td>
        <td><%= post.content %></td>
        <td> <form action="<%= post_url(post) %>" method="post">
          <%= auth_token %>
          <input type="hidden" name="_method" value="delete">
          <input type="hidden" name="sub_id" value="<%= @sub.id %>">
          <input type="submit" value="delete post">
        </form> </td>
      </tr>
    <% end %>
  </tbody>
</table>

W5D2/redditclone/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

W5D2/redditclone/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

W5D2/redditclone/app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>username
    <input type="text" name="user[username]">
  </label>

  <label>email
    <input type="text" name="user[email]">
  </label>

  <label>password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="Create New User">
</form>

W5D2/redditclone/app/views/users/show.html.erb
<h1>Users#show</h1>

The user page for <%= @user.username %>