W4D4/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resources :bands
  resource :session, only: [:new, :create, :destroy]
  resources :not_found, only: [:index]
  resources :albums
end

W4D4/music_app/app/models/album.rb
class Album < ApplicationRecord
  validates :title, :year, :band, presence: true
  validates :live_album, nil: false
  validates :live_album, inclusion: {in: [true, false]}

  belongs_to :band,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Band
end

W4D4/music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Album
end

W4D4/music_app/app/models/user.rb
class User < ApplicationRecord
  after_initialize :ensure_session_token!
  validates :email, :session_token, :password_digest, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  attr_reader :password

  def self.find_by_credentials(email, pass)
    user = self.find_by(email: email)

    if user.nil?
      return nil
    elsif user.is_password?(pass)
      return user
    end
    nil
  end

  def self.generate_session_token!
    SecureRandom::urlsafe_base64
  end
  
  def is_password?(pass)
    bc_pass = BCrypt::Password.new(self.password_digest)
    bc_pass.is_password?(pass)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token!
    self.save!
  end

  def ensure_session_token!
    self.session_token ||= User.generate_session_token!
  end

  def password= (new_password)
    @password = new_password
    digest = BCrypt::Password.create(new_password)
    self.password_digest = digest.to_s
  end
  
end

W4D4/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :user_params, :current_user, :logged_in?

  private

  def current_user
    session_token = session[:session_token]
    user = User.find_by(session_token: session_token)
    user
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def logged_in?
    !!(current_user)
  end

  def log_in_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def log_out_current_user!
    return if current_user.nil?
    current_user.reset_session_token!
    session[:session_token] = ""
  end
end

W4D4/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  
  def index
    @bands = Band.all
    render :index
  end

  def create
    band = Band.new(band_params)
    if band.save
      redirect_to band_url(band)
    else
      flash.now[:errors] = band.errors.full_messages
      render :new
    end
    nil
  end

  def new
    @band = Band.new
    render :new
  end

  def edit
    @band = Band.find_by(id: params[:id])
    unless @band.nil?
      render :edit
    else
      render 'shared/not_found', status: 404
    end
  end

  def show
    @band = Band.find_by(id: params[:id])
    unless @band.nil?
      render :show
    else
      render 'shared/not_found', status: 404
    end
  end

  def update
    band = Band.find_by(id: params[:id])
    if band.update(band_params)
      redirect_to band_url(band)
    else
      flash[:errors] = band.errors.full_messages
      redirect_to edit_band_url(band.id)
    end
  end

  def destroy
    band = Band.find_by(id: params[:id])
    unless band.nil?
      band.destroy
    end
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end

end

W4D4/music_app/app/controllers/not_found_controller.rb
class NotFoundController < ApplicationController
  def index
    render :index
  end
end

W4D4/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    email = user_params[:email]
    password = user_params[:password]
    user = User.find_by_credentials(email, password)
    if user.nil?
      flash.now[:errors] = ["Invalid email or password"]
      render :new
    else
      log_in_user!(user)
      redirect_to user_url(user.id)
    end
  end

  def destroy
    log_out_current_user!
    redirect_to new_session_url
  end
end

W4D4/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to user_url(user.id)
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end
 
  #TODO: bounce user if id doesn't match current session's user

  def show
    @user = User.find_by(id: params[:id])
    if @user.nil?
      redirect_to :new
    end
    render :show
  end
  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W4D4/music_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"form_authenticity_token\">".html_safe
  end
end

W4D4/music_app/app/views/bands/_form.html.erb
<% unless @band.persisted? %>
  <% form_method = "post" %>
  <% form_action = bands_url %>
<% else %>
  <% form_method="patch" %>
  <% form_action = band_url(@band.id) %>
<% end %>

<form action="<%= form_action %>" method="post">
  <input type="hidden" name="_method" value="<%= form_method %>">

  <label for="band_name">Band Name: </label>
  <input type="text" id="band_name" name="band[name]" value="<%= @band.name %>">
  <br>  
  <input type="submit" value="Save">
  
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

W4D4/music_app/app/views/bands/_index_list_item.html.erb
<ul>
  <section>
    <li> <a href="<%= band_url(band.id) %>"><%= band.name %></a></li>
    <form action="<%= edit_band_url(band.id) %>" method="post">
      <input type="hidden" name="_method" value="get">
      <input type="submit" value="edit">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    </form>
  </section>
</ul>

W4D4/music_app/app/views/bands/_show.html.erb
<ul>
  <section>
    <li> <%= band.name %> </li>
    <form action="<%= edit_band_url(band.id) %>" method="post">
      <input type="hidden" name="_method" value="get">
      <input type="submit" value="Edit Band">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    </form>
  </section>
</ul>

W4D4/music_app/app/views/bands/edit.html.erb
<header>
  <h2> Edit <%= @band.name %></h2>

  <form action="<%= band_url %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <input class="delete-button" type="submit" value="Delete">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  </form>
</header>
<%= render 'shared/errors' %>
<%= render 'form' %>

W4D4/music_app/app/views/bands/index.html.erb
<header class="index_header">
  <h2> All Bands </h2>

  <form id="new_band_button" action="<%= new_band_url %>" method="post">
    <input type="hidden" name="_method" value="get">
    <input type="submit" value="add">
    <input type="hidden" name="authenticity_token" value="<% form_authenticity_token %>">
  </form>
</header>

<% @bands.each do |band| %>
  <%= render "index_list_item", band: band %>
<% end %>

W4D4/music_app/app/views/bands/new.html.erb
<h2> Add a New Band </h2>

<%= render 'shared/errors' %>

<%= render 'form' %>

W4D4/music_app/app/views/bands/show.html.erb
<header>
  <h2> <%= @band.name %> </h2>

  <form action="<%= edit_band_url %>" method="post">
    <input type="hidden" name="_method" value="get">
    <input type="submit" value="Edit">
    <input type="hidden" name="authenticity_token" value="form_authenticity_token">
  </form>
</header>

W4D4/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav>
      <h1 class="home-title"> <a href="<%= bands_url %>">Music App</a> </h1>
      <aside class="log-in-out-buttons">
        <% if logged_in? %>
          Signed in as <%= current_user.email %>
        <% end %>
        <%= render 'shared/log_in_out' %>
      </aside>
    </nav>

    <%= yield %>
  </body>
</html>